# Generated by Django 3.2.13 on 2022-12-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
